services:
  - type: web
    name: super-admin-backend
    env: node
    plan: starter
    buildCommand: "cd backend && npm install"
    startCommand: "node backend/server.js"
    envVars:
      - key: DB_HOST
        fromSecret: DB_HOST
      - key: DB_USER
        fromSecret: DB_USER
      - key: DB_PASSWORD
        fromSecret: DB_PASSWORD
      - key: DB_NAME
        fromSecret: DB_NAME
      - key: SUPER_ADMIN_KEY
        fromSecret: SUPER_ADMIN_KEY

  - type: static
    name: super-admin-frontend
    plan: starter
    staticPublishPath: frontend